- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: MESSAGE_HOST
  value: "{{servicename}}-MESSAGE-HOST"
  type: "keyvault"
- key: MESSAGE_USER
  value: "{{servicename}}-MESSAGE-USER"
  type: "keyvault"
- key: MESSAGE_PASSWORD
  value: "{{servicename}}-MESSAGE-PASSWORD"
  type: "keyvault"
- key: NOTIFY_API_KEY
  value: "{{servicename}}-NOTIFY-API-KEY"
  type: "keyvault"
- key: NOTIFY_MESSAGES_TEMPLATE_ID
  value: "{{servicename}}-NOTIFY-MESSAGES-TEMPLATE-ID"
  type: "keyvault"
- key: POSTGRES_HOST
  value: "sndadpdbsps4401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "sndadpinfmi4401-ffc-sfd-messages-processor"
- key: PROCESSOR_SUBSCRIPTION_ADDRESS
  value: "fcp-sfd-messages-processor"
- key: PROCESSOR_TOPIC_ADDRESS
  value: "fcp-sfd-messages"